# -*- coding: utf-8 -*-
"""sales_summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQQ0W33buK_uFklyrL-9yAA2uMIWHaVE
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt


conn = sqlite3.connect('sales_data.db')
cursor = conn.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY,
    product TEXT,
    quantity INTEGER,
    price REAL
)
''')

sample_data = [
    ('Apple', 10, 1.5),
    ('Banana', 20, 0.8),
    ('Orange', 15, 1.2),
    ('Apple', 5, 1.5),
    ('Banana', 10, 0.8),
    ('Orange', 8, 1.2)
]

cursor.executemany('INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)', sample_data)
conn.commit()

query = '''
SELECT product, SUM(quantity) AS total_qty, SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
'''

df = pd.read_sql_query(query, conn)

print("\nSales Summary:")
print(df)

df.plot(kind='bar', x='product', y='revenue', legend=False)
plt.title('Revenue by Product')
plt.xlabel('Product')
plt.ylabel('Revenue')
plt.tight_layout()
plt.savefig('sales_chart.png')
plt.show()

conn.close()

